corowne/lorekeeper

- .gitignore
- app/Services/CharacterManager.php
- public/css/lorekeeper.css
- resources/views/character/_image_info.blade.php
- resources/views/character/_image_js.blade.php
- resources/views/character/_tab_notes.blade.php
- resources/views/character/character_logs.blade.php
- resources/views/home/_character.blade.php
- resources/views/home/_sidebar.blade.php
- resources/views/home/characters.blade.php
- resources/views/home/myos.blade.php
- resources/views/pages/_dashboard.blade.php
- resources/views/widgets/_bank_select.blade.php
- resources/views/widgets/_bank_select_row.blade.php
- resources/views/world/index.blade.php
Fixes bugs such as appearance issues on mobile, an issue with nested modals, as well as various tweaks and fixes.
> Various tweaks and bugfixes

- app/Http/Controllers/Characters/MyoController.php
When attempting to visit a myo/{id} where the character is not a myo, it will redirect to the character page of that character. Allows for permalinking of characters, especially those created as MYO slots.
> Redirect non-MYO to Character page

- app/Http/Controllers/Admin/SubmissionController.php
- app/Models/Submission/Submission.php
- resources/views/admin/submissions/index.blade.php
Adds the ability to sort submissions by oldest or newest
Oldest is the default
Also fixes a bug where searching all categories would result in no prompts showing
> Add newest/oldest sorting for submissions

- app/Http/Controllers/Admin/Characters/CharacterController.php
- app/Http/Controllers/Admin/Characters/CharacterImageController.php
- app/Http/Controllers/Characters/DesignController.php
- app/Services/CurrencyManager.php
- resources/views/admin/index.blade.php
- resources/views/admin/masterlist/_create_character_subtype.blade.php
- resources/views/admin/masterlist/create_character.blade.php
- resources/views/character/admin/_edit_features_modal.blade.php
- resources/views/character/admin/_edit_features_subtype.blade.php
- resources/views/character/admin/_upload_image_subtype.blade.php
- resources/views/character/admin/upload_image.blade.php
- resources/views/character/design/_features_subtype.blade.php
- resources/views/character/design/features.blade.php
- resources/views/layouts/app.blade.php
- routes/lorekeeper/admin.php
- routes/lorekeeper/members.php
Added Jquery/Ajax to check when species is changed and show only the subtypes for that specific species.
Also, some other bugfixes.
> Subtypes for proper species + Bugfixes

- app/Http/Controllers/Admin/Characters/CharacterController.php
- app/Http/Controllers/ShopController.php
- app/Services/ShopService.php
added ability to remove ALL items from a store with no issues. Added AUth check to shop for guest viewing item info. Added MYO redirect when deleting an MYO slot.
> Shop stock view and MYO redirect

- app/Http/Controllers/BrowseController.php
- resources/views/shops/_purchase_history_row.blade.php
- Fix invisible characters being visible to logged-out and non-permissioned users
- Fix error on attempting to view a purchase log relating to a deleted shop
> Small Bugfixes

- app/Http/Controllers/Characters/CharacterController.php
- app/Models/Character/CharacterTransfer.php
- app/Services/CharacterManager.php
- database/migrations/2020_09_21_205840_transfer_reason.php
- resources/views/admin/masterlist/_transfer.blade.php
- resources/views/character/transfer.blade.php
> User Transfer reasons

- app/Http/Controllers/BrowseController.php
- app/Http/Controllers/Characters/CharacterController.php
- app/Http/Controllers/WorldController.php
- app/Models/Gallery/GallerySubmission.php
- app/Services/SubmissionManager.php
- resources/views/admin/loot_tables/create_edit_loot_table.blade.php
- resources/views/galleries/submission.blade.php
- resources/views/widgets/_gallery_thumb.blade.php
- resources/views/world/items.blade.php
Misc:
- Move gallery submission literature thumb text to attribute
Bugs fixed:
- Fix loot table display name getting whole, formatted display name rather than raw name from database
- Fix item entry/page shops display
- Fix gallery submission comment mention code
- Character galleries not sorted newest to oldest
- Add tag stripping to gallery submission literature thumbs, fixing some display bugs
- Set submission addon count to take stack count if the stack exists but no quantity is provided (seems to occur sometimes if the quantity == the stack count for indeterminate reasons)
- Fix MYO, masterlist sublist artist/designer search
Tested/working live, no additional actions necessary
> Misc bugfixes

- app/Services/CharacterManager.php
as discussed in discord, gives back any user added items to a design update when initiating a transfer
> Adding service to give-back any user items used in a draft

- app/Helpers/AssetHelpers.php
- app/Http/Controllers/BrowseController.php
- app/Models/Gallery/GallerySubmission.php
- resources/views/browse/_masterlist_content.blade.php
> Adding search by url / alias and jpg to mimes

- app/Http/Controllers/Users/BookmarkController.php
- app/Models/Gallery/GallerySubmission.php
- resources/views/account/bookmarks.blade.php
- resources/views/account/notifications.blade.php
- resources/views/galleries/submission.blade.php
- resources/views/home/inventory.blade.php
- resources/views/pages/credits.blade.php
- resources/views/user/inventory.blade.php
New:
- Add sort options to character bookmarks
Misc:
- Put back gallery submission display features relating to prompt ID
- Add credit for masterlist image automation
- Add confirmation modal before deleting all notifications
- Make user inventory sections collapseable
Tested locally; no further actions required
> Misc QoL features and tweaks

- resources/views/user/_currency_log_row.blade.php
> Fixing +CURRENCY count when it should be -CURRENCY

- app/Http/Controllers/Admin/Users/UserController.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/HomeController.php
- app/Http/Controllers/Users/AccountController.php
- app/Http/Middleware/CheckAlias.php
- app/Models/User/User.php
- app/Models/User/UserSettings.php
- app/Services/UserService.php
- database/migrations/2021_04_29_175640_add_user_birthday.php
- resources/views/account/settings.blade.php
- resources/views/admin/users/user.blade.php
- resources/views/auth/birthday.blade.php
- resources/views/auth/blocked.blade.php
- resources/views/auth/register.blade.php
- resources/views/user/profile.blade.php
- routes/lorekeeper/admin.php
- routes/lorekeeper/members.php
- routes/web.php
what it says on the tin! Tested locally across multiple accounts.
> Add User Birthdays

- app/Http/Controllers/Characters/CharacterController.php
- app/Http/Controllers/ShopController.php
- app/Models/Character/CharacterProfile.php
- app/Models/User/User.php
- app/Services/ItemService.php
- resources/views/account/bookmarks.blade.php
- resources/views/character/_header.blade.php
- resources/views/shops/_stock_modal.blade.php
New:
- Add display of an item's count in user's inventory (when logged in) to shop stock modal
Bugs Fixed:
- Cannot edit/delete character bookmarks from list
- "Can be named" switch for item categories unable to be un-set
- Add validation to/tighten security on character profile link extension; fixes #93 
Tested locally; no additional actions required.
> Misc Fixes/Tweaks

- app/Models/Item/Item.php
Specifically loot tables were angry with the new update but this seems to have fixed that
> Bugfix for site being angry there's no rarity

- app/Http/Controllers/Admin/Users/UserController.php
- app/Models/User/User.php
- resources/views/account/settings.blade.php
- resources/views/admin/users/user.blade.php
- resources/views/user/profile.blade.php
- Add admin side logging for birth date changes
- Change birthday column to a Carbon instance
- Fix bug where selectMonth would not show the actual birth month
- Change columns of profile to be two columns instead of birthday all on its own - and adding Clear style to divs after it so they don't get harassed by the avatar's float.
- Encase all user account forms in cards, user and admin side. This is because with more and more user forms in the settings, it is becoming very easy on non-customized LK to differentiate between the different forms.
> Edits to new Birthday functionality + User settings forms

- app/Services/SalesService.php
Also clean up function to account for $characters var being unnecessary to pass to processCharacters
Thank you to @JuniJwi for the fix!
> Fix processCharacters bug when creating sales

- app/Http/Controllers/PermalinkController.php
- app/Models/Comment.php
- app/Traits/Commentable.php
- resources/views/comments/_comment.blade.php
- resources/views/comments/_perma_comments.blade.php
+ add report button to _perma_comments
> Show deleted comments and children of deleted comments

- resources/views/sales/_character.blade.php
Tested locally, no further action required
> Fix displaying uncategorized traits on characters attached to sales posts

- app/Services/SalesService.php
Just adding some extra checks to make sure it doesn't do any processing unless slug is set. No additional actions necessary.
> Fix creating/updating sales without characters

- app/Helpers/Helpers.php
- config/lorekeeper/sites.php
> fixing regex for discord

- app/Services/CharacterManager.php
taps tin
prevents new characters / images erroring with new checkAlias by filtering all null values before being checked
still effectively adds credits (tested on local, thrown on live at approx time of post)
> fix undefined offset: 0 error

- resources/views/admin/grants/item_search.blade.php
I’m not sure how users find these things sometimes tbh. Just adding a couple of issets!
> Fix very occasional bug searching items sitewide

- resources/views/character/design/addons.blade.php
Applies when no addons have been added/saved. Tested live
> Fix error viewing design update draft addons

- app/Http/Controllers/Admin/Users/UserController.php
- app/Http/Controllers/Users/SubmissionController.php
- app/Services/SubmissionManager.php
- resources/views/admin/users/user_update_log.blade.php
- Redirect new submission/claim back on service error
- Add check to submission creation for negative currency (Fixes #124)
- Fix error formatting clear alias log data (Fixes #123)
- Add a safety check to user update log re above (Fixes #123)
Tested locally, no further action required
> Fix reported bugs

- resources/views/sales/_character.blade.php
- resources/views/user/_ownership_log_row.blade.php
Misc:
- Hide sales character link (e.g. to a comment) if comments on the sales post itself aren't yet visible (that is, the sales post is in preview state)
Bugs Fixed:
- Attempting to view a user's ownership logs when a deleted character is present errors
Tested live - No further action necessary
> Small fixes/tweaks

- resources/views/galleries/index.blade.php
$loop->final should be $loop->last or it errors
> Final -> Last

- app/Helpers/Helpers.php
I was looking at helpers and VSC started hollering at me about brackets, so I fixed it.
> fix: syntax error

- resources/views/admin/users/user.blade.php
- resources/views/user/_sidebar.blade.php
there's checks inside the blade for this and users with edit user perm should be able to edit users even if they cant edit rank
> fix: incorrect permission to edit users

- README.md
Just updating wiki links to point to the new wiki.
> docs: update readme for 2.0.0

- app/Http/Controllers/Admin/RaffleController.php
- app/Models/Raffle/RaffleTicket.php
- app/Services/RaffleManager.php
- resources/views/admin/raffle/ticket_index.blade.php
- changes ticket entry to be a clone form w/ user selection / alias entry / ticket quantity entry fields (so it can add appropriate number of tickets, including multiple if desired, for each user)
- also adjusts so that off-site users are referred to more generically. this is changed from assuming these are all dA aliases
No further actions needed; tested locally.
> feat(raffles): improve ticket entry form

- resources/views/widgets/_inventory_select.blade.php
- impacts submissions, design updates, trades
Dragin idk if you have a cleaner fix for this but even if so, if it's not immediately forthcoming this will have to do in the interim
Tested locally; no further action necessary
> fix: 'invalid quantity' when attaching items

- resources/views/widgets/_inventory_select.blade.php
- resources/views/widgets/_inventory_select_js.blade.php
- cleaner fix for the quantity error; works as intended now
Fixes #174
Discovered the culprit, was a syntax error. this includes cleaning up the earlier bandaid fix
Tested locally; no further action required
> fix: inventory filters, quantity error

- app/Models/Character/Character.php
- app/Models/Character/CharacterImage.php
- jpeg is specified in accepted file types but not jpg
Iirc this has come up before elsewhere?
> fix(characters): issue with .jpg files

- resources/views/character/admin/_edit_features_modal.blade.php
This new function is then called upon loading the modal and when the species is changed.
Fixes https://github.com/corowne/lorekeeper/issues/224
> Seperates refreshing of subtype into a function

- public/css/lorekeeper.css
- resources/views/auth/register.blade.php
- resources/views/comments/_comment.blade.php
- resources/views/comments/_perma_comments.blade.php
First time doing a PR request so let me know if I did it wrong : )
Seeking to first fix an issue where comments would not be restricted in size. Second issue I am seeking to fix is an issue where selecting birthday date during registration would shrink on mobile, effectively making it troublesome to confirm selected birthday is correct. Verified on local both work correctly (hence the second commit haha).
> Small UI Update

- app/Services/ShopService.php
- app/Services/SubmissionManager.php
- Fix claims not being able to be created with raffle tickets
- should not affect prompt submissions
- corresponds to raffle tickets being available when creating a claim
- Fix shop desc being unable to be cleared
Tested locally; no further action necessary
> Small fixes

- resources/views/user/characters.blade.php
- resources/views/user/sublist.blade.php
- Swapped Encoding to UTF-8 from ANSI
- Made it look consistent with Masterlist
(PR is also possible for main branch, but I figure develop is the better call.)
> User Profile Character/Sublist pages edited

- public/css/lorekeeper.css
Images in world entry descriptions weren't being constrained on smaller screens. This adds that constraint (and consequently uses the same styles being applied to the .parsed-text class which is pretty similar.
> Constrain world entry images

- resources/views/comments/_comment.blade.php
- resources/views/comments/_perma_comments.blade.php
- resources/views/galleries/submission.blade.php
- resources/views/user/_profile_content.blade.php
As per title. Extremely minor fix.
> Making alt text for avatars consistent

- app/Helpers/Helpers.php
- app/Http/Controllers/Characters/CharacterController.php
- resources/views/character/_image_info.blade.php
- resources/views/pages/credits.blade.php
- resources/views/user/_profile_content.blade.php
- yarn.lock
A small Quality of Life feature, making sure users know how to use the character mention.
Also added a mention for character thumbnails, as well as adding new user mentions, including avatars this time.
> Extended Mentions

- app/Helpers/Helpers.php
- app/Http/Controllers/HomeController.php
- app/Providers/AppServiceProvider.php
- app/Providers/Socialite/ToyhouseProvider.php
- config/lorekeeper/sites.php
- config/services.php
Due to extremely unfortunate current events. See #300 for details.
I've basically just cherry picked the specific merge for these files (not sure how else to pull this off), not much shooouuuuuuuld be affected I think.
> Prioritised merge of TH OAuth2 compatibility from develop

- app/Http/Controllers/Admin/Data/SpeciesController.php
- app/Http/Controllers/BrowseController.php
- app/Http/Controllers/Characters/DesignController.php
- app/Http/Controllers/WorldController.php
- app/Models/Species/Species.php
- app/Services/SpeciesService.php
- database/migrations/2022_12_22_205505_add_is_visible_to_specieses.php
- resources/views/admin/specieses/create_edit_species.blade.php
Adds a visible toggle for Species.
Will hide the species in the encyclopedia, search function of the masterlist/sublist/myo list and design update.
> feat(species): add visibility toggle

- resources/views/world/features.blade.php
This is an old bug that seems to have avoided EVERYONE'S attention...
Simple fix, too.
> fix: Search Traits by Category cancelling out after each search

- resources/views/browse/_masterlist_content.blade.php
There's a hr tag that _SHOULD_ only show up when the other options are available.. that is outside of that if.
Very minor fix, but figured I'd throw it up anyway.
> Fix:(browse): Misplaced hr tag

- app/Http/Controllers/Users/UserController.php
- config/lorekeeper/extensions.php
- resources/views/pages/credits.blade.php
- resources/views/user/_profile_content.blade.php
Adds aliases on userprofile.
Feature is toggleable, and turned off by default.
> feat(user): Added aliases on userprofile feature

- resources/views/admin/masterlist/create_character.blade.php
- resources/views/character/admin/_edit_features_modal.blade.php
- resources/views/character/admin/upload_image.blade.php
- resources/views/character/design/features.blade.php
This will make it easier to add multiple new trait slots.
(and an mb-2 class to make it look nice.)
> patch(features): Putting the Add Trait button ABOVE the trait list

- resources/views/admin/features/features.blade.php
- resources/views/admin/items/items.blade.php
- resources/views/admin/specieses/specieses.blade.php
- resources/views/admin/specieses/subtypes.blade.php
Just adds a little slashed eye icon in the admin lists, so it's easy to see what's not visible. :)
> Marks off items, traits, species and species subtypes as not-visible in admin lists.

- app/Http/Controllers/Admin/SalesController.php
- app/Services/SalesService.php
- resources/views/home/_character.blade.php
Displays warning on characters hidden from public view!
> patch(sales): Allows hidden characters to be added to sales.

- app/Http/Controllers/BrowseController.php
Yeah, I dunno. Looks out of place and @itinerare agreed it should've been inside the brackets.
So. A PR to do just that. :shrug:
> fix(browse): Apparently this is supposed to be in here.

- resources/views/pages/credits.blade.php
> patch(credits): Added wiki links to my extensions missing them and re-alphabetized

- app/Http/Controllers/WorldController.php
- config/lorekeeper/extensions.php
- resources/views/pages/credits.blade.php
- resources/views/world/_species_entry.blade.php
- resources/views/world/species_features.blade.php
- routes/lorekeeper/browse.php
Adds the ability to have modals pop up when you click on a trait on the trait index with the traits description instead of navigating to a separate page.
> Feat(Species Trait Index): Adds modals when clicking on traits

- app/Policies/CommentPolicy.php
- resources/views/admin/reports/report.blade.php
- resources/views/browse/users.blade.php
User categories aren't a thing, so switches it to rank.
> bugfix: Fix default selection for user masterlist sorting.

- app/Http/Controllers/Users/InventoryController.php
- resources/views/home/inventory.blade.php
- resources/views/home/inventory_full.blade.php
- routes/lorekeeper/members.php
It's purely in Home, as it's for a user to see, in one easier glance, exactly which items they have where.
It's similar to Account Search, but instead of making you look through items you may not even have, it simply shows everything you do have.
> New Feature: Adds a page that shows the Full Inventory

- app/Models/Sales/SalesCharacter.php
- app/Services/SalesService.php
- Fixes missing minimum options for ota and xta
- Also adds consistent stylization for ota and xta alongside pwyw
> Fix(Sales): Bug fix regarding sales

- app/Helpers/AssetHelpers.php
common complaint
it doesnt add danger flash, happy to move flashes into the boxrewardstring if needed
> Notify user of no reward

- app/Services/DesignUpdateManager.php
- app/Services/Item/BoxService.php
- app/Services/Item/SlotService.php
Minor comment errors. Nothing more, nothing less. Thanks to @AW0005 for additional suggestions.
> fix(services): Minor comment errors

- app/Services/CharacterManager.php
Copies the if logic to switch to imagick into the cropThumbnails function so the benefits are gotten there as well!
> Bug(Thumbnails): Add Imagick switch to thumbnails

- app/Services/CharacterManager.php
It was pointed out that I forgot thumbnail cropping in my earlier PR... whoops |D
Also, another shot at the MYO image format fix, since apparently the prior one didn't do the job (though by all rights it should have).
> fix(characters): MYO image format, thumbnail webp support fixes

- app/Http/Controllers/WorldController.php
- app/Models/Feature/Feature.php
- config/lorekeeper/extensions.php
- resources/views/pages/credits.blade.php
- resources/views/world/_sidebar.blade.php
- resources/views/world/index.blade.php
- resources/views/world/universal_features.blade.php
- routes/lorekeeper/browse.php
@CH3RVB's Universal Trait Index extension - but now merged into develop.
Additionally, it contains the same modal system the Species Trait Index has, for consistency, as well as the same options to disable it.. And of course, does not display hidden traits.
> Universal trait index merged into core

- app/Services/PromptService.php
Hash wasn't included in the `Array::only` list so it wasn't getting saved for prompts
> Bug(Prompts): Image hash not saving

- app/Services/UserService.php
- add missing use statement (fixes a bug reported in the server)
- clean up deactivation function (use DesignUpdateManager, set user where absent)
`$staff` is set at the start of the deactivation function if null (to the user performing the operation if it's not being done by staff), so it should always be set/is safe to use by default.
> fix(users): clean up UserService

- app/Models/Raffle/RaffleTicket.php
- app/Models/User/UserSettings.php
A couple seem to have slipped through the cracks in the first pass.
> fix: convert remaining dates to casts

- resources/views/shops/shop.blade.php
> feat(shops): Add shop image to meta-img, if it exists

- resources/views/admin/reports/report.blade.php
- resources/views/home/_report_content.blade.php
Almost as if #708's changes didn't go through to develop nor release branch...
Though the command and the changes to the permalinkController _are_ there..
> fix(reports): Somehow the comment type was missing?

- resources/views/admin/reports/report.blade.php
Minor optimization. Leaves the entire scripts section alone if it's closed, rather than using the scripts section either way.
Also, changed how the buttons are assigned, JQuery wise.
> optimize(reports): Minor optimization towards reports

- app/Helpers/Helpers.php
- config/lorekeeper/sites.php
Title.
Also, added icons to the sites missing..
As well as FurAffinity as site- as we've had a few designers from there it seemed logical to add and I finally figured I might as well drop it in core LK as well.
> Add site icons to off-site users

- app/Models/Character/Character.php
- config/lorekeeper/extensions.php
- resources/views/pages/credits.blade.php
- resources/views/user/_characters.blade.php
Exactly as it says on the tin. Small minibadges to be added to the User side's Characters/MYO Slots pages (or sublists, also works.)
> Adds minibadges to the user's characters page

- resources/views/pages/credits.blade.php
Moved them around again- alphabetize, checked around better which were toggleable, etc..
Will do this again after next Sunday, there's a develop branch ext that needs to be put in the right spot as well, but I'd rather wait until this change has been moved there :)
> Credits page re-ordening

- resources/views/pages/credits.blade.php
> Merging release into dev + credits fix

- resources/views/pages/credits.blade.php
> fix(credits): u and w extensions to swap back correctly please

- resources/views/admin/reports/report.blade.php
Probably just escaped a bit in one of the prior edits; easy fix either way.
> fix(reports): include parent scripts in scripts section

- app/Http/Controllers/Admin/Data/ItemController.php
- app/Models/Item/Item.php
- app/Services/ItemService.php
- database/migrations/2024_05_13_020617_add_deletable_to_items.php
- resources/views/admin/items/create_edit_item.blade.php
- resources/views/character/_inventory_stack.blade.php
- resources/views/home/_inventory_stack.blade.php
Some items are just meant to be kept. Or.. otherwise. :)
> Feat(items): Add option to block deletion

- app/Console/Commands/AddSiteSettings.php
- app/Http/Controllers/Users/BankController.php
- app/Http/Controllers/Users/InventoryController.php
- resources/views/home/_inventory_stack.blade.php
- resources/views/home/bank.blade.php
Don't want your users to directly transfer items or currency, and instead pass it through a trade?
Aight, just change your site settings. :)
> Feat(items/currency): Block direct transfer by site settings

- app/Http/Controllers/Users/BankController.php
- app/Http/Controllers/Users/InventoryController.php
- app/Http/Controllers/Users/UserController.php
- app/Services/ItemService.php
- resources/views/admin/items/create_edit_item.blade.php
- resources/views/home/_inventory_stack.blade.php
Forgot for a moment my testing environment is different from the dev environment, and that I shouldn't make last minute text edits.
Hotfix for 500 errors caused by BOTH #948 and #949 - my bad, sorry.
> Hotfix(new features)

- resources/views/home/_sidebar.blade.php
Liked Comments url should be "comments/liked" rather than "liked-comments"
> fix liked comments

- app/Http/Controllers/WorldController.php
- config/lorekeeper/extensions.php
- resources/views/admin/currencies/create_edit_currency.blade.php
- resources/views/admin/features/create_edit_feature.blade.php
- resources/views/admin/galleries/create_edit_gallery.blade.php
- resources/views/admin/grants/user_currency.blade.php
- resources/views/admin/items/create_edit_item.blade.php
- resources/views/admin/masterlist/create_character.blade.php
- resources/views/admin/news/create_edit_news.blade.php
- resources/views/admin/pages/create_edit_page.blade.php
- resources/views/admin/prompts/create_edit_prompt.blade.php
- resources/views/admin/sales/create_edit_sales.blade.php
- resources/views/admin/shops/_stock.blade.php
- resources/views/admin/sublist/create_edit_sublist.blade.php
- resources/views/admin/users/_create_edit_rank.blade.php
- resources/views/prompts/_prompt_entry.blade.php
- resources/views/user/_characters.blade.php
- resources/views/user/character_designs.blade.php
- resources/views/user/characters.blade.php
- resources/views/user/myo_slots.blade.php
- resources/views/user/sublist.blade.php
- resources/views/world/_sidebar.blade.php
- resources/views/world/_species_entry.blade.php
- resources/views/world/index.blade.php
- resources/views/world/species_features.blade.php
- resources/views/world/universal_features.blade.php
- routes/lorekeeper/browse.php
Fixes included in this PR:
- For consistency, every single admin page has cols and form-group merged. I found this to be a common occurrence and this saves on a bit of space.
- There was a single redundant bracket on `resources/views/prompts/_prompt_entry.blade.php`. It's now removed. (This was found by to iinkt on the LK discord.)
- I found a minor mistake on the Character Designs/Art page; the art version's breadcrumbs had the wrong url.
- I realized the Character Designs/Art page shares most of it's code with the characters, myos and sublist pages. I have thus reused the same code.
- Also for these pages, I added an 'userpage_exts' check, this so that extension additions exclusive to userpage characters have a space to be added. This is left open with a blade comment. (Mostly done with …
> Fix: Optimalizations and redundancy removal

- app/Http/Controllers/Users/UserController.php
> fix(controller): Minor mislabel on UserController

- resources/views/shops/_stock_modal.blade.php
- resources/views/shops/shop.blade.php
fixes Undefined array key "" error when putting an item without category in a shop.
Adds img-fluid to the shop stock modal so they stay in their box.
> Small shop bug fixes

- app/Models/Comment/Comment.php
> feat: make comment links become clickable to prevent weird views

- app/Models/Comment/Comment.php
https://discord.com/channels/678909186683437056/1278276989408514058/1278276989408514058
> fix(comments): stop url parsing on wysiwyg images

- app/Services/CharacterManager.php
Subtype was unchanged from subtype_id despite the change to subtype_ids. This is very likely to result in errors.
For consistency I've pulled the lines from another function earlier in the file, this is also why species and rarity are affected by this change, though no function should be altered.
> fix(character manager): HandleCharacterImage function consistency

- app/Console/Commands/ConvertCharacterSubtype.php
Based on #1047 that coincidentally passed just minutes ago!
- make _third_ subtype support work out of the box
That's all!
> feat(commands): add third subtype support in subtype conversion command

- resources/views/admin/raffle/ticket_index.blade.php
I am still surprised I messed this one up, so I gave it another once-over and fixed the table.
Thanks to @ScuffedNewt for letting me know.
> fix(admin): Raffle Table messup

- resources/views/pages/credits.blade.php
I'll do the same for the develop branch soon as this one is in, I'm think I saw a few Newt missed when they did this in the character warnings PR.
> fix(credits): Update all references to ne-wt to ScuffedNewt

- resources/views/admin/raffle/ticket_index.blade.php
- resources/views/pages/credits.blade.php
..Yeah, gonna be honest, found nothing but the very two name changes I had _just_ done in release (#1060), so consider this primarily a release => develop merge. 🤷
>  fix(credits): Update all references to ne-wt to ScuffedNewt (dev)

- app/Services/CharacterManager.php
- app/Services/TradeManager.php
Exactly as it says on the tin. Just merging in the release changes from approx 2 weeks back. :)
> Release merge to dev
