corowne/lorekeeper

.gitignore, app/Http/Controllers/Admin/SubmissionController.php, app/Services/SubmissionManager.php, resources/views/admin/submissions/submission.blade.php, resources/views/home/_submission_content.blade.php
Move staff comments for submissions out of the modal and into the main page body, as well as enable staff comments for either acceptance or rejection of a submission.
=> Submissions-Exp

app/Models/Submission/Submission.php, app/Services/DeviantArtService.php, app/Services/SubmissionManager.php, database/migrations/2020_06_01_124250_add_parsed_submission_comments.php, resources/views/admin/submissions/submission.blade.php, resources/views/home/_submission_content.blade.php
Bugs fixed:
- dA api request scope unnecessarily large
Misc:
- Staff comment entry on submissions now uses Tiny editor and is parsed in accordance with this
- Note: Displays parsed staff comments if present and non-parsed if only those are present for backwards compat
Requires php artisan migrate!
=> Change staff comments to rich text, restrict dA api request scope

app/Http/Controllers/BrowseController.php, app/Http/Controllers/Characters/CharacterController.php, app/Http/Controllers/Users/BookmarkController.php, app/Models/Character/Character.php, app/Models/Character/CharacterBookmark.php, app/Models/Notification.php, app/Services/BookmarkManager.php, app/Services/CharacterManager.php, config/lorekeeper/notifications.php, config/lorekeeper/settings.php, database/migrations/2020_10_30_170108_add_gift_writing_status_to_characters.php, resources/views/account/bookmarks.blade.php, resources/views/account/bookmarks/_create_edit_bookmark.blade.php, resources/views/browse/_masterlist_content.blade.php, resources/views/character/edit_profile.blade.php, resources/views/character/profile.blade.php
- Add gift writing status to characters (yes/no/ask first)
- Add gift writing status to bookmarks and add accompanying notification
- Add gift writing status search to masterlist
- Fix bug with gift art status notification
- Add settings for:
- Resetting character trading status, gift art status, and gift writing status on transfer (enable/disable, defaults to disabled)
- Resetting character name and profile on transfer (enable/disable, defaults to disabled)
- Clearing MYO slot name on MYO submission approval (enable/disable, defaults to disabled)
Requires migration, have tested locally -- settings in config/lorekeeper/settings.php
=> Add gift writing status to characters, etc.

app/Http/Controllers/Admin/SalesController.php, app/Models/Sales.php, app/Services/SalesService.php, database/migrations/2020_11_02_204925_add_delayed_comments_to_sales.php, resources/views/admin/sales/create_edit_sales.blade.php, resources/views/sales/_sales.blade.php, resources/views/sales/sales.blade.php
- Adds a toggle (open/closed) to sales posts; mostly just impacts display (the result is displayed in the post title)
- Adds a 'comments open at' time/date field; if this is set (and in the future), comments won't be displayed for the post until that point. (A message is instead displayed beneath it on the post's page itself saying that comments aren't open yet, and will open at (x ) time; uses the pretty_date helper).
- If a post is set to 'open' and there is a set future 'comments open at' time, the title will display 'preview' instead of 'open'
- Staff with permissions to edit sales posts are still able to see the comments interface, so that if any set-up needs to be done before a sale opens, it can be done without any need to scramble
- Add the ability to 'bump' extant sales posts …
=> Add open/closed toggle, delayed comments, and bumping to sales posts

app/Services/CharacterManager.php, config/lorekeeper/settings.php, resources/views/admin/masterlist/create_character.blade.php, resources/views/character/admin/_reupload_image_modal.blade.php, resources/views/character/admin/upload_image.blade.php, resources/views/character/design/image.blade.php
Credit for original code to https://github.com/itinerare / @itinerare 
Adds option in settings to automate thumbnail process, making images square and resizing them to thumbnail size.
Replaces the image cropper, but allows user to still upload their own thumbnail.
=> Automate image process to make images and thumbnails square

routes/lorekeeper/members.php
added a missing route preventing items from being removed or deleted from character inventories
=> Fix character inventory edits leading to a 404

app/Http/Controllers/Users/UserController.php, resources/views/admin/designs/index.blade.php, resources/views/admin/users/index.blade.php, resources/views/home/bank.blade.php
- Fix design update index display showing vote counts erroneously
- Fix admin user index link not directing to user edit page
- Fix user profile inventory display showing items with a count of 0
Fixing misc small issues as reported by folks/the bug report channel. No specific actions needed.
=> Misc small bugfixes

app/Http/Middleware/RedirectIfAuthenticated.php
Now it redirects to the actual home page instead of the 404 page 'home' when attempting to go to the registration url when logged in.
#56
=> Fix redirection to 'home' when visiting '/register' while logged in

app/Http/Controllers/Characters/MyoController.php
Add 'user_reason' to MyoController for postTransfer.
Previously, when attempting to user-transfer a MYO slot, it would give a "undefined index: user_reason" error.
=> Add 'user_reason' to MyoController for postTransfer.

app/Http/Controllers/Users/SubmissionController.php, app/Http/Controllers/WorldController.php, app/Models/Item/Item.php, app/Services/ItemService.php, database/migrations/2021_01_08_230640_add_released_to_items.php, resources/views/admin/items/create_edit_item.blade.php
- This toggle, when off, hides items from user view (in item index in world, item pages in world, and when making submissions/claims)
- It is overridden by a stack of the item existing
Tested locally/live - Requires migrate
=> Add an "is released" toggle to item editing (w/ extra fields enabled)

app/Http/Controllers/Characters/MyoController.php, app/Http/Controllers/Users/UserController.php, app/Models/Gallery/GalleryCollaborator.php, app/Services/CharacterManager.php, app/Services/ShopService.php, composer.json, resources/views/user/_ownership_log_row.blade.php, resources/views/user/characters.blade.php, resources/views/user/profile.blade.php
Fixed majority of issues (did not fix / attempt to fix issue #38)
All fixes where tested locally, logged in and out for those that could be affected by auth
=> Develop Issues fix PR

app/Http/Controllers/Users/UserController.php
removed get() from first line, putting it into the variable area since otherwise laravel does not recognise it as a scope
=> Hotfix to prevent 500 error when trying to view myo slots as non-admin

app/Services/ItemService.php
- Consolidates  character limit into `populateCategoryData` as it was duplicated in two different functions that use `populateCategoryData`
- Fixes inability to disable category character ownership (use case: accidental enabling)
--- Thoughts: Should this handle currently character-owned items?
Tbh I am not sure on the usage of the tertiary and the standalone variable? But it was how it was before so I left it and used the same method for character ownership.
=> Character Items Bugfix

config/lorekeeper/extensions.php, resources/views/character/_image_info.blade.php, resources/views/pages/credits.blade.php
- A config toggle to group traits by category on the Character Profile page (image info.)
- Adjusting Credits page into bootstrap columns
- Also changed "Extensions" and [Nothing] to "Core Extensions" and "Installed Extensions" to help with potential confusion.
=> Toggleable - Group Traits by Category on Character Profiles

app/Http/Controllers/PermalinkController.php
Permalinks used to throw 500 errors if either the comment didn't exist, or for instance the thing it was commented on was deleted.
Now it just will throw a 404!
=> Adding missing 404 to Permalinks

app/Models/Character/CharacterCategory.php, app/Models/Currency/Currency.php, app/Models/Feature/Feature.php, app/Models/Feature/FeatureCategory.php, app/Models/Item/ItemCategory.php, app/Models/News.php, app/Models/Prompt/Prompt.php, app/Models/Prompt/PromptCategory.php, app/Models/Rank/Rank.php, app/Models/Rarity.php, app/Models/Sales.php, app/Models/Shop/Shop.php, app/Models/SitePage.php, app/Models/Species/Species.php, app/Models/Species/Subtype.php
A lot of names for pages, posts, prompts.. all of them had a character limit of 25. I have changed this to 100, where possible. Every single changed variable has been checked if the database supported it, and they have.
Altered are:
- News Post names
- Sales Post names
- Prompt names
- Prompt Category names
- Page names
- Rank names
- Species names
- Species Subtype names
- Shop names
- Rarity names
- Item Category names
- Features names (Note: These are traits)
- Feature Category names
- Currency names
- Character Category names
I have not altered the limits for abbreviations, keys, prefixes and the like, as 25 characters seems like a good maximum for short hand of the full name.
Item name limit has also not been changed as this was already at 100 characters.
The database for all of …
=> Changed all name variables to have a maximum of 100 characters, as opposed to 25.

app/Helpers/AssetHelpers.php, app/Http/Controllers/Admin/SubmissionController.php, app/Http/Controllers/Users/SubmissionController.php, app/Models/Submission/SubmissionCharacter.php, app/Services/SubmissionManager.php, config/lorekeeper/extensions.php, resources/views/admin/submissions/submission.blade.php, resources/views/home/_submission_content.blade.php, resources/views/home/create_submission.blade.php, resources/views/js/_character_select_js.blade copy.php, resources/views/js/_character_select_js.blade.php, resources/views/pages/credits.blade.php, resources/views/widgets/_character_select.blade.php, resources/views/widgets/_character_select_entry.blade.php
Expands character rewards for submissions and claims.
Left in code for `currency_id` etc in case it is used in extensions etc.
Two config flips: 
- Enable/Disable
- Default non-character-held rewards to owner character/submitter
=> Character Reward Expansion

app/Console/Commands/AddSiteSettings.php
Site settings can be added with a single line of code instead of having to copy and modify an entire logic block.
**Example**: `$this->addSiteSetting("site_setting_key", 1, "0: does nothing. 1: does something.");`
=> add new site settings with one line instead of multiple.

app/Http/Controllers/Admin/Data/LootTableController.php, app/Models/Loot/Loot.php, app/Models/Loot/LootTable.php, app/Services/LootService.php, config/lorekeeper/extensions.php, database/migrations/2021_03_28_172111_add_item_category_info_to_loots.php, resources/views/admin/items/create_edit_item.blade.php, resources/views/admin/loot_tables/create_edit_loot_table.blade.php
Following my asking after the notion almost a year ago now, haha, I did it.
New:
- Adds item category as an option for loot tables; an item is selected at random from those in the category.
- Optional/toggleable: Adds rarity criteria for both items and item categories as options for loot tables; these allow rolling from all items/all items in a category that are (=/</>/<=/>=) any given rarity that exists on the site. Note that this expects rarities to be numeric, though strings should still work with `=`.
- Optional/toggleable: By default this uses whereRaw() for filtering which works consistently on local, but on DH (and presumably with software that supports JSON natively) a cleaner where() searching within the JSON that way was more consistent; thus, I included an option to switch to …
=> Add item categories, rarity conditions to loot table options

resources/views/layouts/app.blade.php
Adds a header opting a site out of Google's FLoC. While it's not a security issue, it _is_ a privacy issue; this is in the wake of github itself, for instance, adding this header to this site as well as to github pages.
As a prompt response to the matter seems prudent-- regardless of the ultimate fate of the technology-- I feel it practical to merge this into master in the vein of a hotfix, though it is not technically one since it's not fixing a bug per se.
Tested locally - Requires no further action
=> Opt out of FLoC

app/Services/LinkService.php
As with #12, but updated to suit the new system. Other providers may need to be adjusted as appropriate in the future; however, I do not know their scopes offhand. The basic method should work for each, however-- setScopes() overwrites scopes specified within the individual provider packages and so is a ready way to curtail any unnecessary access without needing to modify things at/around the package level.
Tested live, no further actions necessary.
=> Re-reduce dA request scope to only username

app/Http/Controllers/GalleryController.php, app/Models/Gallery/Gallery.php, resources/views/galleries/_sidebar.blade.php, resources/views/galleries/index.blade.php
Adds a visible() scope to galleries and correctly checks against it.
Tested live, no further actions required
=> Fix bug with galleries being (incorrectly) visible

CONTRIBUTING.md
Add contribution info within the repo with basic guidelines and a link to the relevant article on the wiki, as github displays a message to first-time contributors if the file is present.
=> Add contribution info

resources/views/character/_tab_stats.blade.php
I added the config setting with the sales character stuff but it is understandably hard to find a dollar symbol in the haystack that is the entirety of the LK source, haha.
=> Make character sale value use currency symbol from config file

app/Services/SubmissionManager.php, routes/web.php
fix: submission approval will now log to the correct user instead of the approving admin when including currency from user's bank
This issue likely arose because $user was only the submitter for a short while before it was switched back into $staff within the above block.
patch 2 includes removing the duplicate birthday name for the web route which was previously blocking `php artisan route:cache` from running.
=> fix: will now log to the correct user

resources/views/admin/pages/create_edit_page.blade.php, resources/views/galleries/create_edit_submission.blade.php
- I've been wanting a "view page" button for site pages for eons and decided to add it. Most other things have previews while pages do not, so a link is necessary imo and not just for develop
- Adds `$submission->prompt_id` to the create_edit_submission file so that when an admin edits a file, they don't accidentally strip it of its prompt.
=> Fix to gallery submissions + "View Page" button addition

app/Helpers/AssetHelpers.php
Casting $data['art_bonus'] to an array will guarantee that the foreach input will be an array
=> fix: art bonuses no longer error when 'multiple' is set to false

.github/dependabot.yml
- checks weekly for non-security-critical dependency updates
- creates PR for merge into develop
Though it only impacts develop, this only takes effect when it's in the repo's default branch, thus,
=> chore: setup dependabot config

resources/views/admin/sales/_character_select_entry.blade.php
More a UX fix than anything; hides the "is open" toggle for sales characters if there's only one character attached to the sales post, since it's largely relevant when there are multiple characters associated.
No action necessary; tested live.
=> fix(sales): 'is open' for chars even when only one

app/Services/CharacterManager.php, app/Services/SubmissionManager.php, app/Services/TradeManager.php, resources/views/widgets/_inventory_select.blade.php, resources/views/widgets/_inventory_select_js.blade.php
When submitting Prompts, if an incorrect URL (or other form validation error) is used on the first attempt to submit, users will be returned to the form, with the fields seemingly repopulated with their previous input. However, if they then try to submit again without manually reselecting the inventory addons, the entire stack of the selected item will be used in the submission.
Other changes as a result of this fix:
- stack_quantity is now keyed by the stack_id, which helps in properly refilling the form on failed submit
- If stack_quantity is not set, an error is thrown instead of defaulting to the use of the whole stack; this error check has also been added to the CharacterManager (for design updates) and TradeManager
Tested locally.
=> Fix for errored inventory addon forms not refilling the old data

app/Helpers/Helpers.php, app/Http/Controllers/Admin/Data/CurrencyController.php, app/Http/Controllers/Admin/Data/FeatureController.php, app/Http/Controllers/Admin/Data/GalleryController.php, app/Http/Controllers/Admin/Data/ItemController.php, app/Http/Controllers/Admin/HomeController.php, app/Http/Controllers/Admin/Users/UserController.php, app/Models/AdminLog.php, app/Services/CharacterCategoryService.php, app/Services/CharacterManager.php, app/Services/CurrencyManager.php, app/Services/CurrencyService.php, app/Services/FeatureService.php, app/Services/GalleryManager.php, app/Services/GalleryService.php, app/Services/InventoryManager.php, app/Services/ItemService.php, app/Services/ReportManager.php, app/Services/SubmissionManager.php, app/Services/TradeManager.php, app/Services/UserService.php, config/lorekeeper/admin_sidebar.php, database/migrations/2021_07_21_103622_create_admin_log_table.php, resources/views/admin/logs.blade.php, resources/views/galleries/gallery.blade.php, routes/lorekeeper/admin.php
discussed on disc, the ONLY thing i can think of potentially being an issue is $user not being defined in an area i may have missed though I tried my best to test everywhere I added it. May also be some spots that should have logging that I've neglected
=> feat: Extension/admin logs (also merging of latest release/release-2.0.0)

public/css/lorekeeper.css
Currently, if pagination gets too long it breaks the width of the mobile view. Adding flex-wrap to the pagination property in css fixes that!
=> Add flex-wrap to pagination to keep it from breaking mobile view.

app/Models/News.php, app/Models/Sales/Sales.php, composer.json, config/feed.php, resources/views/layouts/_footer.blade.php, resources/views/layouts/app.blade.php, routes/web.php
Folk in the server indicated interest as well, so putting this forward for inclusion. 
By default sets up for two feeds: one for news, one for sales, which should work automatically. Also adds links to them in the footer, but feed readers should be able to detect all feeds configured for a site regardless.
Tested locally; requires `composer update`.
=> feat: implement news/sales rss feeds

app/Http/Controllers/Admin/Data/PromptController.php, app/Http/Controllers/Admin/SubmissionController.php, app/Services/Item/BoxService.php, resources/views/admin/items/tags/box_post.blade.php, resources/views/admin/prompts/create_edit_prompt.blade.php, resources/views/admin/submissions/submission.blade.php, resources/views/home/create_submission.blade.php, resources/views/home/submissions_closed.blade.php, resources/views/widgets/_loot_select.blade.php, resources/views/widgets/_loot_select_row.blade.php
- this is in the name of compatibility between different exts
- and to reduce support time demanded by issues with that
Going forward, ext authors can merely add support for a new entity to the `_loot_select` and `_loot _select_row` views... It's a "messy" fix but I think it's worthwhile.
Tested locally, no further action required.
=> refactor: move loot_select info fetching to views

app/Models/User/UserAlias.php
Without this, links were simply not working because of the dot missing in the URL.
=> Tiny fix for the Tumblr alias

resources/views/character/design/image.blade.php
fixes the 404 image for cropper on design updates currently in queue / out of draft phase. Tested locally, works as intended (only edits when modify thumbnail is checked).
=> fix: missing image url for cropper on admin design updates

app/Http/Controllers/Admin/Data/PromptController.php, app/Http/Controllers/PromptsController.php, app/Models/Prompt/Prompt.php, app/Services/PromptService.php, app/Services/SubmissionManager.php, database/migrations/2022_02_19_014311_add_admin_only_to_prompts.php, resources/views/admin/prompts/create_edit_prompt.blade.php, resources/views/admin/prompts/prompts.blade.php
Adds a toggle to prompt creation/editing to make a prompt visible and submittable to only by staff. Might be niche, but the changes are very minor, so I figured it'd be worth PRing.
Tested locally/live, requires `php artisan migrate`.
=> feat(prompts): staff-only prompt toggle

app/Http/Controllers/HomeController.php, app/Providers/AppServiceProvider.php, app/Providers/Socialite/ToyhouseProvider.php, config/lorekeeper/sites.php, config/services.php
It's here!! Big thank you to TH admin for getting OAuth2 up and working 🙏💖💕
Go to [https://toyhou.se/~developer](https://toyhou.se/~developer) to set up a client and grab your keys.
This setup was a bit more finicky than the others (code-wise), and there are a few things to note while using it:
- This can't be tested from localhost (there might be workarounds but it might still be annoying, I set up an instance on my server to test it)
- When creating a new app, the redirect URL has to be very specifically `http://your-site.com/auth/callback/toyhouse` as it doesn't seem to use wildcard matching. You may have to enter both non-www and www variants if you use them, etc.
Aside from these, no database/composer updates required. Please add to .env:
```
TOYHOUSE_CLIENT_ID= …
```
=> Add Toyhouse OAuth2 authentication

resources/views/admin/sales/_character_select_js.blade.php, resources/views/galleries/_character_select_js.blade.php, resources/views/js/_character_select_js.blade copy.php, resources/views/js/_character_select_js.blade.php
I was playing around with making prompts, and ended up getting very confused when I kept getting the "Character does not exist" error on submission.
Turns out I kept thinking I had to click the "Add Character" button to get the character's details to populate in after entering the code, when I really should have just been clicking outside of the input.
For me that really doesn't feel intuitive, and so this is a tiny bug fix / feature? that changes the character selection input to be "onInput" rather than "onChange" so it updates as a user is typing. It does mean that you get an inline error about the character not existing until you've finished typing the code, but I find that to be more helpful.
I made this change to `_character_select_js.blade copy.php` to be thorough, although I'll be …
=> Fixes Character Selection being unclear

resources/views/admin/masterlist/_transfer.blade.php, resources/views/home/_transfer.blade.php
This fixes an issue where the Transfer Log will no longer load up and gives an error
"Trying to get property 'url' of non-object" if a character that had been in a transfer was later deleted (and therefore no longer exists to pull information from).
I hide the thumbnail entirely if the character doesn't exist and swap out the `h3` content with "Character Deleted".
=> Bug:: Transfer log has errors if Character was Deleted

app/Services/CharacterManager.php, app/Services/Service.php
Fixes the following situation:
1. Non-Staff user has an item with the slot tag
2. Non-Staff user attempts to use item with the slot tag to get a slot
3. SlotService attempts to call `createCharacter` in the CharacterManager to create the slot
4. User passed to `createCharacter` is not staff, so when it tries to log it as an adminAction, it fails.
=> Bug:: Issue fix for ItemSlots not being usable

app/Http/Controllers/PromptsController.php, resources/views/prompts/_prompt_entry.blade.php, resources/views/prompts/prompt.blade.php, routes/lorekeeper/browse.php
I've got this as an extension right now:
http://wiki.lorekeeper.me/index.php?title=Extensions:Prompt_Permalink
But it was mentioned in discord that this would be a good candidate for including in core.
=> Prompt permalinks

app/Http/Controllers/PromptsController.php, app/Models/Prompt/Prompt.php, resources/views/prompts/prompts.blade.php
Adds an additional filter to the prompts page to be able to filter for prompts that are still open, or closed prompts (based on start and end date).
=> Prompts Open/Closed Filter

app/Models/User/User.php
Adds rank icons to the 'regular' displayName function and vice versa, adds the banned strike-through as well as the lowered opacity for deactivated accounts to the comments version of the displayName function.
=> Update differences between DisplayName functions

config/lorekeeper/settings.php, resources/views/character/design/image.blade.php, resources/views/pages/credits.blade.php
Adds option to hide uploading thumbnails from users, and users only.
Works only if the previous automation feature is also enabled.
Altered credits to separate it from Watermarking, as while this is an addition on top, it always looked off to me that it was all on the same line in the credits.
=> Masterlist Image Automation addition

app/Http/Controllers/NewsController.php, app/Http/Controllers/SalesController.php, resources/views/news/_sidebar.blade.php, resources/views/news/index.blade.php, resources/views/news/layout.blade.php, resources/views/news/news.blade.php, resources/views/sales/_sidebar.blade.php, resources/views/sales/index.blade.php, resources/views/sales/layout.blade.php, resources/views/sales/sales.blade.php
Sidebars display Recent News/Sales on posts, and 'On This Page' on the index pages.
For Sales specifically, both posts and the index pages also have a section 'For Sale', which are only __open__ sales.
Original inspiration, most of the code and idea by @itinerare.
=> Adds sidebars to News and Sales

resources/views/layouts/app.blade.php
The standard is as described in [this post](https://www.deviantart.com/team/journal/A-New-Directive-for-Opting-Out-of-AI-Datasets-934500371). 
This doesn't guarantee that images won't be scraped right now - it's up to the AI people to respect the standard on their end, but if they do, then the entirety of an LK-based site should be protected.
=> Add deviantART's noai and noimageai directives

app/Services/UserService.php
uc_first() is a function that doesn't exist.
ucfirst() does.
=> fix(deactivation): Function doesn't exist, fixed

app/Http/Controllers/NewsController.php, app/Http/Controllers/SalesController.php
Was updating stuff and got an error on the News page. It's a pretty minor change so I hope I didn't just miss something?
Tested locally.
EDIT: updated to fix the Sales page too.
=> fix: missing use statement for Facades/View

resources/views/comments/_actions.blade.php
Specifically if a user was ID 32 they would be able to feature or un-feature a comment on News or Sales of ID 32 instead of just their own profile.
=> Bug(Comments): Users able to feature comments they shouldn't

app/Http/Controllers/Characters/CharacterController.php, package-lock.json
If a LK site was using `'character_pull_number' => 'all'` in settings and tried to use the new previous and next buttons a lot of characters would have oddly missing buttons to the non-sequential numbers between categories. This adjusts the prev and next buttons to respect the LK setting and only filter by category if it's set that way.
=> Adjust Prev and Next Buttons to respect when 'character_pull_number' is 'all',

app/Http/Controllers/Characters/CharacterController.php, config/lorekeeper/extensions.php, resources/views/character/_header.blade.php
Have been thinking for a while to update the previous and next buttons.. so they no longer skip over the gaps- displaying no previous or next button just because in a sequence of 1-2-4-5 there is no 3, so no previous on 4 and no next on 2.. that's silly.
Spoke about it with @itinerare who quickly produced code, but it required some testing.. and some fixing. And that's what I did.
Also special mention to @AW0005 whose recent edit to the code made me consider doing this. :)
=> Feat(character): Updating previous and next buttons to skip the gaps

resources/views/admin/features/features.blade.php, resources/views/admin/items/items.blade.php, resources/views/admin/prompts/prompts.blade.php, resources/views/prompts/prompts.blade.php, resources/views/world/prompts.blade.php
Just a teeny bug fix that I noticed, where the selected category on the prompts filter wasn't "sticking" on clicking search because it's value was being set to name instead.
=> bug(prompts): Category Filter value being set to name

composer.json
Reportedly, Dreamhost is pushing upgrading sites to PHP 8.1 due to support ending for 7.4... which is understandable for security etc reasons, and probably an idea, but annoying from a logistical standpoint.
However this is salvageable without too significant changes since Laravel 8 supports PHP 8.1 at maximum and takes surprisingly few changes to arrive at a compatible set of packages. The main things are just allowing Laravel (within the same major version) and doctrine/dbal (fine since the issue we were prior having with it looks to be resolved anyhow) to update.
This has been tested a bit already, and looks to be working alright, hence the PR, but more is always welcome.
Necessary actions are just updating PHP itself and running composer.
=> PHP 8.1 upgrade

resources/views/pages/credits.blade.php
As title.
When I updated the variable names to add the swap for previous and next (being in front or in the back), I forgot to update the variable on the credits page. This fixes that.
=> bug(credits): incorrect variable name, would display always as disabled

resources/views/character/inventory.blade.php, resources/views/home/inventory.blade.php, resources/views/user/inventory.blade.php
- Are now equivalent in being able to open and close per category.
- Categories are now id'd by.. category id, rather than name, which lead to a few problems.
- Arrow now correctly shows as open rather than closed, which was a minor pet peeve that bothered me.
I did this mostly for consistency between the three types of inventory pages, and also.. one of the sites I work on has a category that's like `Named Character's Items` .. and the `'` broke the collapse.
And yes, the arrows started as 'collapsed' bothered me to no end. So I also fixed that. They now start as 'open', as categories are, by default, open.
=> fix(inventories): fix for user, home and character inventories

app/Services/ItemService.php
Since the `$image` variable wasn't being passed to the `populateData` function the code to delete an existing image on an item was never being run.
=> bug(items): item images weren't deleting

app/Services/DesignUpdateManager.php, resources/views/character/design/image.blade.php
This fixes two things:
1. If you were in design submission and had supplied an image and artist credits but you got an error (for example by providing an image with a wrong format or an image that was too large) the browser auto-populates the hidden form elements for the credits with what had been previously picked and since those hidden elements were kept inside the form, they would be duplicated on hitting the submit button the second time. So I moved them to be outside of the form.
2. In the process of fixing the above I realized that I'd get an error if I attempted to only change the credits without uploading a new image, so I fixed that with a better if check on thumbnail processing as well.
=> Bug(Design Submission): Duplicated Credits & Saving Credits w/o image

app/Http/Controllers/Users/AccountController.php
Fixes an issue where the validation was keeping users who had registered with alias login from later adding an email and password login if they wanted.
=> Bug(AliasLogin): Add email and pw after alias registration

resources/views/admin/rarities/create_edit_rarity.blade.php
Used world._entry when world._rarity_entry is more commonly used- also added the two variables that are passed along normally as well.
=> Fix(world): Wrong entry type for rarity

app/Services/UserService.php, resources/views/account/settings.blade.php
.gif avatars should upload fine now, whether it's the first avatar, or the second or third, etc, and should not create a 500 error at all.
=> Bug(Settings): Fix .gif Avatars causing 500 error

resources/views/shops/shop.blade.php
Shops with no image specified were still adding the image html and showing a broken image icon instead of hiding it.
=> Bug(Shops): Shops with no image will show broken image icon

resources/views/character/inventory.blade.php, resources/views/home/inventory.blade.php, resources/views/home/inventory_full.blade.php, resources/views/user/inventory.blade.php, resources/views/widgets/_inventory_view_js.blade.php
- Added Summarized View to Home, User and Character inventories, similarly to the Masterlist view.
- Also fixed minor change on Full Inventory, and added a tag symbol for named items.
This kind of view for the other inventories was originally suggested by @AW0005 in https://github.com/corowne/lorekeeper/pull/669#pullrequestreview-1578925415 :)
=> Feat(Inventories): Summarized View

app/Services/CharacterManager.php
Having found that you cannot make MYO slots because of an incorrect url issue, I investigated how this happened and found it was this use of the asset() function as opposed to the public_path() function.
I've done my research and there is not a single service that uses asset(), except the character manager. So I hereby propose this fix.
This admittedly only fixes the use of MYO slots on localhost. On a live site, this change has no effect. But this should make testing easier, at least.
=> Fix(MYOs): Allows character images to work locally

resources/views/inventory/_box.blade.php
prevents double clicking / rapid clicking on boxes to produce extra items
=> Box Duplication Bug / Exploit

app/Console/Commands/UpdateCommentTypes.php, app/Http/Controllers/PermalinkController.php, resources/views/admin/reports/report.blade.php, resources/views/home/_report_content.blade.php
As on the tin... building on my work wrt gallery submissions but making it... not exclusive to them.... Should be more extensible for the odd instance where these comment types are needed down the road as well.
Also includes a command (`php artisan update-comment-types`) to handle already-extant comments.
Tested a bit on local and looks to work as expected.
=> fix(comments): more robust handling for non user-user comments

resources/views/character/design/_header.blade.php
For some reason staff comments on masterlist submissions were set to be viewable by... the prompt submission power? So if you had staff that only did masterlist submissions they probably couldn't see it. This should fix that.
=> Allow Masterlist staff to see each others comments

app/Models/Character/CharacterDesignUpdate.php
Realized while doing some other cleanup that design updates also has a copy of the offending `orderByRaw()` from #746 ...
=> fix(characters): update design update feature ordering

resources/views/sales/_sales.blade.php, resources/views/sales/sales.blade.php
Long story short:
Used the comments link and realized it just went to the sale. Figured a comments anchor would make more sense. Noted that on the page itself it's just a dead span, so I also made that go to the anchor (despite being right below.. consistency tho.)
Also; Didn't like how the "Comments are not open yet" block is right there leaning against the sales, felt it more consistent to give it the same hr treatment. Moved it out of the if and used it for the above link anchor. :)
I labelled this as suggestion because I kinda just went for it without talking about it- it's very minor and if it's not liked, well, there's a decline for a reason. :)
=> Suggestion(sales): Comments anchor and consistency edit

resources/views/character/_header.blade.php
As of the new update, you can copy the character code, or slug, from characters!
...But MYO Slots return their slot name, and that's completely unintended functionality.
=> fix(characters): Hide slug copy from MYO slots

app/Http/Controllers/Users/UserController.php
Noticed there was a line that was consistently removed cause it's been relegated to the construct as shared view..
But - it's still in one section! Ergo, here's a hotfix to remove said line.
=> fix(user/usercontroller): redundant line, possible oversight

app/Console/Commands/UpdateExtensionTracker.php
Linux servers do __not__ like back slashes. (**Boo to `\`!!**)
Linux servers **do** like forward slashes. (**Yay to `/`!!**)
TL;DR No matter how nice it looks locally, it won't run live unless forwardslash.
=> fix(commands): Extension Tracker not working on live due to backslash vs forwardslash

resources/views/user/_sidebar.blade.php
For some reason, set_active does NOT play nice with just using $user->url..
This fixes it by pulling the consistent code from the other section.
Also.. item-logs was currency-logs?? Whoops.
=> fix(user): sidebar set_active fix

resources/views/user/profile.blade.php
Imagine: you know a username, and you visit their profile by just typing their name.
But you forgot to capitalize their name. Now a box appears that their username was changed to "Username", just cause you missed the capitalization.
..Very minor bug, yes, but by forcing the check to be entirely lowercase, it eliminates the messagebox from popping up on missing caps.
=> fix(user): Forced lowercase on name check

app/Models/Gallery/Gallery.php, resources/views/galleries/_sidebar.blade.php
While in a subgallery, the sidebar stopped showing the other subgalleries of it's parent.
This fixes it, and even works for sub-subgalleries.. Though only one level in.
~~This may require more finetuning in the model later, but I figured this is a fine start.~~
I actually added some fixes that makes it instead check for siblings and avunculi. (Aunts and uncles - aka the parent's siblings.)
You can now have up to Three levels in- which marks a vast improvement in my opinion.
=> fix(galleries): Shows subgalleries of parent while in subgallery (and siblings and avunculi!)

app/Console/Commands/UpdateLorekeeperV3.php
While I agreed with providing this command for those that wish to back-hash their image urls, I don't think it's a good idea to assume everyone updating to V3 will inherently want to do this - I certainly wouldn't.
Most existing images likely won't be unreleased content, _and_ it's not uncommon to use the static link to an image in other places of the site, via pages, news, sales, etc. Back-hashing will kill all of those links, which very much may not be expected or remotely wanted by those updating to V3.
So this opts to add that information as a part of the V3 update command and give the option to skip back-hashing images
=> Make back-hashing images optional

resources/views/user/_profile_content.blade.php
Before you ask, 'why not add the h2 class'? It's cause badges do not support it, they require the html heading.
[See bootstrap documentation on badges](https://getbootstrap.com/docs/4.1/components/badge/#headings) - and [even the newer version](https://getbootstrap.com/docs/5.3/components/badge/#headings) is missing it..
...Of course, then I decided- hang on a sec, I should just make it consistent to character status badges, and I did.
=> fix(user): FTO badge unreasonably small

app/Services/RankService.php
Discovered today that if you add a power to a rank, and it's the only power, and you try to remove it, it doesn't remove, because the code that deletes the old powers was only happening if at least one other power was being specified.
=> Allow for removal of last power on a rank

resources/views/world/species_features.blade.php
Clicking either the image, name or rarity returns the modal.. highly annoying!
Even if you just want to copy paste the name, or want to get the rarity specifically, or maybe you want the link to the trait itself- any of these would make the modal pop up!
..Not anymore. This fixes it so only the IMAGE returns the modal, and the name and rarity work like the links they always were.
=> Suggestion: species visual index fix

app/Services/DesignUpdateManager.php
Admin "modify thumbnail" previously would never process because the `$data['image']` wouldn't ever be true in admin processing. This fixes that for my own site.
=> hotfix: Allow admins to recrop thumbnails in Design Update Requests

public/css/lorekeeper.css
The flex direction limit will prevent blocks from stretching the main container since it's set to flex. This is only on #app right now but it should be on main as well.
As for break-word, I think Lorekeeper ships with name length limits, but this prevents cases where users add header blocks to their comments / descriptions / other stuff it'd be odd to impose a limit on. I understand removing that property but definitely recommend keeping flex-direction.
=> Prevent Horizontal Stretch on <main>

resources/views/home/_report_content.blade.php
An incorrect comparison means that if a report ticket was assigned, a user couldn't see comments made by staff on the ticket - you can see even just a few lines down from the change where the same comparison was being done correctly.
=> Bug(Reports): User's couldn't see comments of assigned tickets

app/Models/Feature/Feature.php
Turns out Feature's scopeVisible function was a special snowflake compared to the others so having the same check sent through wasn't working right. This updates it to be the same, and also updates the `getDropdownItems` function since it was originally dependent on the different format.
=> Bug(Visual Trait Index): Hidden Traits were still showing when they shouldn't

app/Services/ShopManager.php
Because otherwise 0.5 because a whole item at half price.
=> Bug(Shops): Round up shop purchase quantity

app/Models/Character/CharacterImage.php
Context: https://discord.com/channels/678909186683437056/1208583607506042992
Anyone on v2 with fullsize images who migrates to v3, wouldn't have the correct extensions in `fullsize_extension` but in `extension` so this makes it backwards compatible.
=> Bug(Images): Old Fullsize images no longer detected

app/Http/Controllers/Admin/Data/FeatureController.php, resources/views/admin/features/features.blade.php
Adds a sorting function to the traits section in the Admin panel.
Fixes #347.
Minor layout edit to be consistent with the Encyclopedia version, as they're quite literally the same thing.
Sort's Oldest First by default, as per standards.
=> feat(admin/features): Sorting traits in admin

resources/views/comments/comments.blade.php
This is not a problem in main, but only in release (and dev) because of the updated comments function.
Without this `@parent`, many pages which have an `@comments` tag will find their scripts function completely non-functional, as the scripts section in the comments page just.. overrides any other.
(For example: The admin side of handling reports, the Assign button did NOTHING.)
=> fix(many): @comments overwriting scripts section

resources/views/world/universal_features.blade.php
This fixes a minor issue where hidden categories would not show up on the Species Visual Index for staff that do have the permission.. of course with appropriate fa-eye-slash marker. :)
I'd have liked to do this differently, like taking the permission from the model, but this seems to be the only way possible.
Though I distinctly count as a bug fix, as this should've been available from the get-go, the Universal Visual Index is a feature that's only on develop, and so this PR goes to develop.
=> fix(world): Unhide hidden categories for appropriate staff on Universal Visual Index

resources/views/world/species_features.blade.php
This fixes a minor issue where hidden categories would not show up on the Species Visual Index for staff that do have the permission.. of course with appropriate fa-eye-slash marker. :)
I'd have liked to do this differently, like taking the permission from the model, but this seems to be the only way possible.
This I distinctly count as a bug fix, as this should've been available from the get-go.
=> fix(world): Unhide hidden categories for appropriate staff on Species Visual Index

resources/views/pages/credits.blade.php
Added wikilinks to the core exts missing them - courtesy of @LostInProgres setting them up.
Also while at it shortened some of my own core exts names (and moved one accordingly).
=> Fix(credits): Missing wikilinks and abbreviated names

config/lorekeeper/admin_sidebar.php
Was looking at this feature and realized that the admin sidebar links hadn't been exposed for the relevant powers.
=> Bug(Admin): New Powers didn't give sidebar access

resources/views/layouts/app.blade.php
The current check 500s on Guests, basically. Let's fix that.
=> fix(maintenance): Errored out on non-users during maintenance

resources/views/admin/items/items.blade.php
...Visibility was always meant to go in front of sort, as to not mess up the original order, and to be consistent otherwise.
Yet here I completely messed that up. My bad. Did not notice until JUST NOW.
(Worst part is that I did it right on the site I admin, but copied it wrong on my dev X_x;..)
=> fix(admin):consistency fix

app/Http/Controllers/Admin/SubmissionController.php, app/Http/Controllers/BrowseController.php, app/Http/Controllers/Characters/CharacterController.php, app/Http/Controllers/Characters/DesignController.php, app/Http/Controllers/GalleryController.php, app/Http/Controllers/HomeController.php, app/Http/Controllers/PromptsController.php, app/Http/Controllers/ShopController.php, app/Http/Controllers/Users/InventoryController.php, app/Http/Controllers/Users/ReportController.php, app/Http/Controllers/Users/SubmissionController.php, app/Http/Controllers/Users/TradeController.php, app/Http/Controllers/Users/UserController.php, app/Http/Controllers/WorldController.php, resources/views/admin/sales/_character_select.blade.php, resources/views/admin/sales/_character_select_entry.blade.php, resources/views/character/character.blade.php, resources/views/character/images.blade.php, resources/views/character/profile.blade.php, resources/views/galleries/_character_select.blade.php, resources/views/galleries/_character_select_entry.blade.php, resources/views/widgets/_character_select.blade.php, resources/views/widgets/_character_select_entry.blade.php
This is a mindless Replace In Files sweep. Be sure to check it over.
Replaces
`Auth::check() ? Auth::user() : null`
with
`Auth::user() ?? null`
This has been discussed and tested prior, though not in all situations.
(See also issue #907 and the resolved convo in PR #822.)
=> Optimization(all): Auth::user() optimization

app/Http/Controllers/WorldController.php
On LKs with high amounts of items/traits, eventually items/traits start duplicating over pages. An item/trait that was halfway page 8 is also at the top of page 9.
And worst of all: When you get to the last page, you definitely have not seen all items/traits. Some of them have just poofed into the ether.
With this ingenious solution I have finally prevented this duplication!
(Note: solution is actually really, really dumb. I can't believe this fixed it.)
=> fix(world): Items and traits duplication issue on encyclopedia

app/Http/Controllers/Users/SubmissionController.php
It checks for `$userGallerySubmissions` on both editing and creating submissions and claims.
The SubmissionController handles this perfectly for submissions- for claims, not as much.
Figured this would be the easiest solution.
=> fix(claims): userGallerySubmissions 500'd claims

app/Http/Controllers/WorldController.php, app/Models/Item/Item.php
Cleans up WorldController slightly and ensures non-released Items can only be seen by staff with the "edit_data" power.
=> fix(world): Staff without edit_data should not be able to see items

resources/views/admin/index.blade.php
Both of the Gallery queues need the "Manage_Submissions" power, but were visible on the main admin panel nonetheless. Let's clear that up. :)
=> fix(admin): Hide Gallery Queues for those who have no access

resources/views/pages/credits.blade.php
Gathering you all here today to add a single link to the credits page.
I think the "Admin Edit Buttons" extension got Lost In The Sauce when adding the credit links,,, since it *was* technically released as an extension So- *gesticulates*
I never know what to put in this box...
Anyways- 
*mic drop*
=> Add in credits for the Admin Edit Buttons Extension

app/Http/Controllers/Users/SubmissionController.php, app/Models/Submission/Submission.php, resources/views/home/_submission_form.blade.php
- Corrected GallerySubmissionCollaborator to GalleryCollaborator model
- Referenced [Item model attribute](https://github.com/corowne/lorekeeper/blob/main/app/Models/Item/Item.php#L294) for getDataAttribute on Submission model to fix undefined array key on new Submissions
=> Bug Fixes for Gallery Submissions on Prompts

config/lorekeeper/notifications.php
'Gallery Submission Rejected' notification was using the wrong url, causing a 404 error when clicked
=> fixing gallery queue url in notif

app/Models/Character/Character.php, package-lock.json
Fixes case found in the discord where if you create a Sale you can't see hidden characters despite having the appropriate permissions as an admin.
=> Bug(Character): Hidden characters not showing for admin

database/migrations/2024_05_16_220813_adjust_database_character_limits.php
As per discussed in #955 - I've altered the columns from a varchar to a text, as those have no limits.
I used a clean lk release environment to see what the correct values were regarding nullable.. Effectively; I did my research. :)
Also tested it on my copy of an existing Lorekeeper: and it does not seem to cause any issues with the database.
Have also tested if it messes anything up on said local by granting myself items and currency: Seems to be working just fine, at least for the items_log, user_items and currencies_log tables.. so I'm fairly convinced this is all done correctly. :)
=> Increased database limits

app/Http/Controllers/Characters/DesignController.php, app/Services/DesignUpdateManager.php, config/lorekeeper/extensions.php, resources/views/character/design/_cancel_modal.blade.php, resources/views/character/design/request.blade.php, routes/lorekeeper/members.php
Adds the ability for users to cancel their own design requests. Optional by way of config. By default it is set to ON.
=> feat: Add ability for users to cancel their own design requests

resources/views/character/_image_js.blade.php
I noticed on my host when editing the credits of a character, the selectize would sometimes act freaky and appear empty/non functional. After digging for a while, I realized that the edit credits modal request gets sent twice. I think the reason is the event listener being duplicated. After removing it, the issue was resolved on my host - no more empty select and double requests.
(I checked the wiki on how to get small fixes in, so I hope I did it right! Sorry if not orz)
=> Remove duplicate edit-credits in js

resources/views/admin/sales/_character_select.blade.php, resources/views/admin/sales/_character_select_entry.blade.php, resources/views/admin/submissions/submission.blade.php, resources/views/galleries/_character_select.blade.php, resources/views/galleries/_character_select_entry.blade.php, resources/views/widgets/_character_select.blade.php, resources/views/widgets/_character_select_entry.blade.php
My first PR, I hope I'm doing everything right!
Noticed that there was still old unused lines of code in the character selection menus concerning submissions, sales, galleries and where you'd have select_entry and select.blade I believe. Didn't do anything nor was linked to any JS and wasn't visible on v3.0.0 unless you had an extension that made it visible because of custom `<a>` classes like Theme Manager.
`remove-character` is the correct class given it's in the JS and the copy file to delete the selected entry when on-click.
=> Fix: Remove old fa-close line from character selection

resources/views/pages/credits.blade.php
In the recent update, a few extension variables switches around, regarding the visual trait indexes.
I completely forgot to fix that in the credits. My bad.
=> fix(credits): Fixing enable/disable on credits page for visual trait indexes

resources/views/character/_image_info.blade.php
Yeah, I don't know why I did this when I originally added the Extended Mentions. I think I didn't think it through well enough.
These two divs are entirely unnecessary, and having the class on them triggers the wysiwyg editor on them once someone tries to edit Notes.
Big ol' whoopsie. An old whoopsie, too.
=> fix(characters): wrong div class in extended mentions

package-lock.json, resources/views/galleries/index.blade.php
The Gallery Index was pulling in all submissions for a gallery before counting them / only taking the top 4 which over time can cause performance issues as the number of submissions in each gallery grows.
This seemed like more of a bug than a feature so I put it on release? But feel free to let me know if I should redirect to develop.
=> Fix Gallery Performance

package-lock.json, resources/views/widgets/_inventory_select.blade.php
If you submit a claim and check and item where the items quantity is being held in another submission (therefore creating an invalid quantity), you'd hit the error on the quantity and then `return redirect()->back()->withInput();`, and with Input would include an empty quantity value causing this line to 500 error instead of appropriately redirecting with the error banner.
=> Fix error on invalid submission

app/Http/Controllers/PermalinkController.php, package-lock.json
If you had a report, and a staff member replied to your comment on a report, the comment permalink in the notification would 404 because it was a "Staff-User" comment and with no break, was also falling into the "Staff-Staff" comment section and 404'ing there because the user was not staff.
=> Fix Permalinks sometimes 404'ing incorrectly

resources/views/world/species_features.blade.php
Noticed the visual trait index is a bit clunky when resizing the window from where you're viewing it, especially on mobile with long images that gets heavily squished (example at hand below on a clear v3 branch).
This is just a small change that removes the set height and sets max-height as 150px (default), and replace the breakpoint of the column so it doesn't show as small on medium screens and resized windows.
=> Fix: Visual Trait Index image resizing on view

app/Http/Controllers/Admin/LogController.php, config/lorekeeper/admin_sidebar.php, resources/views/pages/credits.blade.php, routes/lorekeeper/admin.php
As per #1022, the Log Viewer ext has been added. I think it's important to add the correct credits, as @Cylunny deserves them.
=> fix(credits): Add Cylunny to credits for Log Viewer ext

app/Http/Controllers/PermalinkController.php, package-lock.json
Permalinked comments were pulling all comments into memory before finding the comment actually linked to, which will eventually crash the page with enough comments.
=> Bug(Comments): Permalinks pull all comments into memory

resources/views/admin/files/index.blade.php, resources/views/admin/logs.blade.php, resources/views/admin/loot_tables/_roll_loot_table.blade.php, resources/views/admin/raffle/ticket_index.blade.php, resources/views/admin/sales/sales.blade.php, resources/views/admin/settings/settings.blade.php, resources/views/admin/staff_reward_settings.blade.php, resources/views/admin/users/user_update_log.blade.php
Starting a minor project to get rid of all `<table>`s, to make them Bootstrap instead.
**Files affected by this PR:**
- \resources\views\admin\sales\sales.blade.php
- \resources\views\admin\users\user_update_log.blade.php
- \resources\views\admin\staff_reward_settings.blade.php
- \resources\views\admin\settings\settings.blade.php
- \resources\views\admin\raffle\ticket_index.blade.php
- \resources\views\admin\loot_tables\_roll_loot_table.blade.php
- \resources\views\admin\logs.blade.php
- \resources\views\admin\files\index.blade.php
This particular PR does not cover pages that have sort functions, namely the following:
- \resources\views\admin\submissions\submission.blade.php
- \resources\views\admin\items\create_edit_item.blade.php
- \resources\views\admin\users\ranks.blade.php
- …
=> Fix(admin): Admin Area Bootstrap tables (non-sortables)

resources/views/news/_news.blade.php, resources/views/news/news.blade.php, resources/views/sales/_sales.blade.php, resources/views/sales/sales.blade.php
Each comments block has the id of 'comments', so a specific commentsSection anchor id is no longer necessary.
Then figured I'd update the news side as well, to be more consistent with sales.
=> fix(sales/news): Removed redundant anchor, fixed links and consistency

app/Models/Character/Character.php, app/Models/Character/CharacterImage.php
After hounding @ScuffedNewt about this on #959, it is discovered that Laravel gives a nice `The given value "2mb" does not represent a valid number.` error.
Despite that Laravel documentation at https://laravel.com/docs/10.x/validation#validating-files-file-sizes says that 2mb is a very valid number.
This PR is a temporary hotfix to fix the 'does not represent a valid number' issue, but we need to look into _why_ 2mb isn't accepted and roll this PR back eventually.
=> temp(characters): Need to figure out the problem with filesize validation

config/lorekeeper/admin_sidebar.php, routes/lorekeeper/admin.php
with the recent addition of the Log Viewer, Admin Logs became inaccessible due to duplication (both 'logs')
changed Admin Logs to 'admin-logs' to resolve this conflict
=> change Admin Logs from 'logs' to 'admin-logs'

app/Console/Commands/ConvertCharacterSubtype.php
- make second subtype support work out of the box
- add additional info text around design updates
- add a progress bar for design updates
Technically emerged as a bugfix, but took the opportunity to put some polish on it and head off some future headaches while I was at it. Figured if there was already implicit support, _explicit_/out-of-the-box support was probably the better move and the one that keeps things simpler on the support front.
Tested both with and without second subtype columns, so shouldn't cause issues either way.
=> feat(commands): improve second subtype support in subtype conversion command

app/Http/Controllers/BrowseController.php
"None" subtype search is functionally the inverse of "any" (queries subtype absence). Hybrid + any specific subtype ID, then, searches (inclusively) for characters with the subtype(s) plus others, enabling search for hybrids including a specific subtype.
I also streamlined the hybrid/any query a bit, which (to my understanding) had the side effect of fixing a weird bug arising in some environments.
Additionally, it looks like sublists got missed initially; following squinting at that I decided to just condense all of the character/MYO/sublist search logic into one function, in the interests of making it all easier to maintain.
Someday I will make a PR that doesn't get distracted halfway through...
=> feat(browse): subtype search improvements, masterlist search refactor

resources/views/world/_features_index.blade.php
This variable has been added when I merged the index code, because the Species index shows subtypes- but the other indexes do not.
I can only assume this check was accidentally removed as other code pertaining this variable are still there.
=> fix(world): Reverse trait index showSubtype check removal

app/Services/TradeManager.php
Said in title, a missing `</a>` was messing with currency logs, unsure if it can be applied retroactively but it behaves correctly now.
=> Fix: Missing closing tag
